[tool.poetry]
name = "pedal-core"
version = "0.0.1"
description = ""
authors = ["Lee Harrold <lhharrold@sep.com>"]
license = "ISC"
readme = "README.md"
packages = [{include = "pedal_core"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
